package nfc;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unused")
final class BillingPolicyCommandSupport {
    private BillingPolicyCommandSupport() {}

    static CatalogSelectionState toCatalogSelectionState(Map<String, Object> catalogDocument, String version) {
        Map<String, Map<String, Long>> table = BillingPolicyCatalogSupport.catalogTableFromRemote(
            catalogDocument == null ? null : catalogDocument.get("table")
        );
        String selectedDefaultTransit = BillingPolicyCatalogSupport.normalizeCode(
            String.valueOf(catalogDocument == null || catalogDocument.get("defaultTransitMonthlyCode") == null
                ? ""
                : catalogDocument.get("defaultTransitMonthlyCode"))
        );
        String suggestedVersion = (version == null || version.isBlank())
            ? ("catalog-" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmm")))
            : version + "-copy";
        return new CatalogSelectionState(table, selectedDefaultTransit, suggestedVersion);
    }

    static EditedRow parseEditedRow(String code, String staffText, String nonStaffText) {
        String normalizedCode = code == null ? "" : code.trim();
        if (normalizedCode.isEmpty()) {
            throw new IllegalArgumentException("missing-code");
        }

        try {
            long staff = Long.parseLong(staffText.trim());
            long nonStaff = Long.parseLong(nonStaffText.trim());
            return new EditedRow(normalizedCode, staff, nonStaff);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Please enter numeric values in sen.", ex);
        }
    }

    static Map<String, Object> healthReportPayload(
        String generatedBy,
        String selectedCatalogId,
        String selectedCatalogVersion,
        String workingVersionLabel,
        String defaultTransitMonthlyCode,
        Map<String, Map<String, Long>> workingTable,
        List<String> errors
    ) {
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("generatedAt", LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        payload.put("generatedBy", String.valueOf(generatedBy));
        payload.put("selectedCatalogId", selectedCatalogId == null ? "" : selectedCatalogId);
        payload.put("selectedCatalogVersion", selectedCatalogVersion == null ? "" : selectedCatalogVersion);
        payload.put("workingVersionLabel", workingVersionLabel == null ? "" : workingVersionLabel);
        payload.put("defaultTransitMonthlyCode", defaultTransitMonthlyCode == null ? "" : defaultTransitMonthlyCode);
        payload.put("rowCount", workingTable == null ? 0 : workingTable.size());
        payload.put("requiredCodeCount", BillingPolicyCatalogSupport.REQUIRED_CODES.size());
        payload.put("missingRequiredCodes", BillingPolicyCatalogSupport.missingRequiredCodes(workingTable));
        payload.put("isValid", errors == null || errors.isEmpty());
        payload.put("issues", errors);
        payload.put("table", workingTable);
        return payload;
    }

    static String buildHealthTxt(Map<String, Object> payload, Map<String, Map<String, Long>> workingTable) {
        @SuppressWarnings("unchecked")
        List<String> issues = (List<String>) payload.get("issues");

        StringBuilder sb = new StringBuilder();
        sb.append("Billing Catalog Health Report\n");
        sb.append("============================\n");
        sb.append("Generated At: ").append(String.valueOf(payload.get("generatedAt"))).append("\n");
        sb.append("Generated By: ").append(String.valueOf(payload.get("generatedBy"))).append("\n");
        sb.append("Selected Catalog ID: ").append(String.valueOf(payload.get("selectedCatalogId"))).append("\n");
        sb.append("Selected Catalog Version: ").append(String.valueOf(payload.get("selectedCatalogVersion"))).append("\n");
        sb.append("Working Version Label: ").append(String.valueOf(payload.get("workingVersionLabel"))).append("\n");
        sb.append("Default Transit Monthly Code: ").append(String.valueOf(payload.get("defaultTransitMonthlyCode"))).append("\n");
        sb.append("Rows: ").append(String.valueOf(payload.get("rowCount"))).append("\n");
        sb.append("Required Codes: ").append(String.valueOf(payload.get("requiredCodeCount"))).append("\n");
        sb.append("Valid: ").append(String.valueOf(payload.get("isValid"))).append("\n\n");

        sb.append("Issues\n");
        sb.append("------\n");
        if (issues == null || issues.isEmpty()) {
            sb.append("None\n");
        } else {
            for (String issue : issues) {
                sb.append("- ").append(issue).append("\n");
            }
        }

        sb.append("\nRequired Code Coverage\n");
        sb.append("----------------------\n");
        for (String code : BillingPolicyCatalogSupport.REQUIRED_CODES) {
            sb.append(workingTable.containsKey(code) ? "[OK] " : "[MISSING] ").append(code).append("\n");
        }

        return sb.toString();
    }

    static final class CatalogSelectionState {
        final Map<String, Map<String, Long>> table;
        final String selectedDefaultTransit;
        final String suggestedVersion;

        CatalogSelectionState(Map<String, Map<String, Long>> table, String selectedDefaultTransit, String suggestedVersion) {
            this.table = table;
            this.selectedDefaultTransit = selectedDefaultTransit == null ? "" : selectedDefaultTransit;
            this.suggestedVersion = suggestedVersion == null ? "" : suggestedVersion;
        }
    }

    static final class EditedRow {
        final String code;
        final long staff;
        final long nonStaff;

        EditedRow(String code, long staff, long nonStaff) {
            this.code = code;
            this.staff = staff;
            this.nonStaff = nonStaff;
        }

        Map<String, Long> toTableRow() {
            Map<String, Long> row = new LinkedHashMap<>();
            row.put("staff", staff);
            row.put("nonstaff", nonStaff);
            return row;
        }
    }
}